/**
 * Config Data Test
 */

BEGIN;
SET search_path TO htm, public;
SELECT plan(5);  -- Test count


-- test config() GENERATED BY config_generate()
SELECT has_function('config', ARRAY['text']);
SELECT function_lang_is('config', 'plpgsql');
SELECT volatility_is('config', 'immutable');
SELECT function_returns('config', 'text');
SELECT is(
  config('neuron_count')::INT,
  config('column_count')::INT * config('row_count')::INT,
  'config() neurons = rows * columns OK'
);


SELECT * FROM finish();
ROLLBACK;  -- Don't save test data

