/**
 * Input/SDR Table
 */

CREATE TABLE htm.input (
  id      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW() PRIMARY KEY,
  created TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  length  INT NOT NULL,
  indexes INT[] NOT NULL
);

