/**
 * Input/SDR Table
 */

CREATE TABLE htm.input (
  id        TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW() PRIMARY KEY,
  created   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  modified  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  indexes   INT[] NOT NULL
);

